//
//  Academic License - for use in teaching, academic research, and meeting
//  course requirements at degree granting institutions only.  Not for
//  government, commercial, or other organizational use.
//
//  get_Cv.cpp
//
//  Code generation for function 'get_Cv'
//


// Include files
#include "get_Cv.h"
#include <cmath>
#include <cstring>

// Function Definitions
void get_Cv(const double qv[3], const double qdv[3], double Cv[49])
{
  double t2;
  double t3;

  // GET_CV
  //     CV = GET_CV(qv,qdv)
  //     This function was generated by the Symbolic Math Toolbox version 8.6.
  //     17-Apr-2023 16:26:18
  t2 = std::cos(qv[2]);
  t3 = std::sin(qv[2]);
  std::memset(&Cv[0], 0, 14U * sizeof(double));
  Cv[14] = qdv[2] * (t2 * 5.016614113875 + t3 * 1.5530402125);
  Cv[15] = qdv[2] * (t2 * 2.224265165851475E+15 - t3 * 7.184797878510198E+15) *
    -6.9822619908066486E-16;
  std::memset(&Cv[16], 0, 33U * sizeof(double));
}

// End of code generation (get_Cv.cpp)
