function Jv = get_Jv(qv,qa)
%GET_JV
%    JV = GET_JV()

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    17-Apr-2023 16:26:19

Jv = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,7]);
