function Mv = get_Mv(qv)

%GET_MV
%    MV = GET_MV(qv)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    05-May-2023 11:52:18

phi = qv(3);
t2 = cos(phi);
t3 = sin(phi);
t4 = t2.*1.3554857805;
t5 = t3.*1.3554857805;
t6 = t3.*4.378475871315;
t9 = t2.*4.378475871315;
t7 = -t4;
t8 = -t5;
t10 = -t9;
t11 = t6+t7;
t12 = t8+t10;
Mv = reshape([2.0165e+2,0.0,t11,0.0,0.0,0.0,0.0,0.0,2.0165e+2,t12,0.0,0.0,0.0,0.0,t11,t12,1.209842138233319e+1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.241925e-2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.241925e-2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.241925e-2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.241925e-2],[7,7]);

%% OLD with inertia taken from urdf of summmit_xls and wheels mass of 1.55

% %GET_MV
% %    MV = GET_MV(qv)
% 
% %    This function was generated by the Symbolic Math Toolbox version 8.6.
% %    17-Apr-2023 16:26:18
% 
% phi = qv(3);
% t2 = cos(phi);
% t3 = sin(phi);
% t4 = t2.*5.016614113875;
% t5 = t2.*1.5530402125;
% t6 = t3.*5.016614113875;
% t7 = t3.*1.5530402125;
% t8 = -t4;
% t9 = -t5;
% t10 = -t7;
% t11 = t6+t9;
% t12 = t8+t10;
% Mv = reshape([2.0745e+2,0.0,t11,0.0,2.0745e+2,t12,t11,t12,7.022445651482428],[3,3]);
