function Cv = get_Cv(qv,qdv)
%GET_CV
%    CV = GET_CV(qv,qdv)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    17-Apr-2023 16:26:18

phi = qv(3);
phid = qdv(3);
t2 = cos(phi);
t3 = sin(phi);
Cv = reshape([0.0,0.0,0.0,0.0,0.0,0.0,phid.*(t2.*5.016614113875+t3.*1.5530402125),phid.*(t2.*2.224265165851475e+15-t3.*7.184797878510198e+15).*(-6.982261990806649e-16),0.0],[3,3]);
end