function Jv = get_Jv()
%GET_JV
%    JV = GET_JV()

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    05-May-2023 11:52:18

Jv = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,7]);
